version: '3.3'
services:
  attestation_database:
    container_name: mu_attestation_db
    image: mysql/mysql-server:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: attestation
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3001:3306"
    expose:
      - "3001:3001"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vnetwork

  attestation_service:
    container_name: mu_attestation_server
    build:
      context: ./attestationserver
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    expose:
      - "3002"
    volumes:
      - ./attestationserver:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - attestation_database
    networks:
      - vnetwork

volumes:
    db_data:
networks:
  vnetwork:
    driver: bridge
      